//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCurriculum
{
    using System;
    using System.Collections.Generic;
    
    public partial class phase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phase()
        {
            this.trainings = new HashSet<training>();
        }
    
        public short id { get; set; }
        public string name { get; set; }
        public short start { get; set; }
        public short end { get; set; }
        public string objectives { get; set; }
        public string description { get; set; }
        public short status_id { get; set; }
    
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<training> trainings { get; set; }
    }
}
