//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCurriculum
{
    using System;
    using System.Collections.Generic;
    
    public partial class training_schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public training_schedule()
        {
            this.users_training = new HashSet<users_training>();
        }
    
        public int id { get; set; }
        public int training_id { get; set; }
        public System.DateTime start_date { get; set; }
        public short recurrence { get; set; }
        public Nullable<byte> recurrence_type_id { get; set; }
        public short status_id { get; set; }
    
        public virtual recurrence_type recurrence_type { get; set; }
        public virtual status status { get; set; }
        public virtual training training { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users_training> users_training { get; set; }
    }
}
