//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCurriculum
{
    using System;
    using System.Collections.Generic;
    
    public partial class training_material
    {
        public int id { get; set; }
        public int training_id { get; set; }
        public string link { get; set; }
        public string description { get; set; }
        public short status_id { get; set; }
    
        public virtual status status { get; set; }
        public virtual training training { get; set; }
    }
}
