//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCurriculum
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_training
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int training_schedule_id { get; set; }
        public short recurrence { get; set; }
        public short status_id { get; set; }
    
        public virtual status status { get; set; }
        public virtual training_schedule training_schedule { get; set; }
        public virtual user user { get; set; }
    }
}
